export const CREATE_INTERIOR_REQUEST = "CREATE_INTERIOR_REQUEST";
export const CREATE_INTERIOR_SUCCESS = "CREATE_INTERIOR_SUCCESS";
export const CREATE_INTERIOR_FAIL = "CREATE_INTERIOR_FAIL";

export const GET_INTERIOR_REQUEST = "GET_INTERIOR_REQUEST";
export const GET_INTERIOR_SUCCESS = "GET_INTERIOR_SUCCESS";
export const GET_INTERIOR_FAIL = "GET_INTERIOR_FAIL";

export const INTERIOR_DETAILS_REQUEST = "INTERIOR_DETAILS_REQUEST";
export const INTERIOR_DETAILS_SUCCESS = "INTERIOR_DETAILS_SUCCESS";
export const INTERIOR_DETAILS_FAIL = "INTERIOR_DETAILS_FAIL";

export const UPDATE_INTERIOR_REQUEST = "UPDATE_INTERIOR_REQUEST";
export const UPDATE_INTERIOR_SUCCESS = "UPDATE_INTERIOR_SUCCESS";
export const UPDATE_INTERIOR_FAIL = "UPDATE_INTERIOR_FAIL";

export const DELETE_INTERIOR_REQUEST = "DELETE_INTERIOR_REQUEST";
export const DELETE_INTERIOR_SUCCESS = "DELETE_INTERIOR_SUCCESS";
export const DELETE_INTERIOR_FAIL = "DELETE_INTERIOR_FAIL";

export const INTERIOR_LIST_REQUEST = "INTERIOR_LIST_REQUEST";
export const INTERIOR_LIST_SUCCESS = "INTERIOR_LIST_SUCCESS";
export const INTERIOR_LIST_FAIL = "INTERIOR_LIST_FAIL";

export const CREATE_INTERIOR_RESET = "CREATE_INTERIOR_RESET";

export const UPDATE_INTERIOR_RESET = "UPDATE_INTERIOR_RESET";
